version: "3.9"

services:
  zookeeper:
    image: confluentinc/cp-zookeeper:7.5.0
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
    ports:
      - "2181:2181"

  kafka:
    image: confluentinc/cp-kafka:7.5.0
    depends_on:
      - zookeeper
    environment:
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092,PLAINTEXT_HOST://localhost:9094
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
    ports:
      - "9094:9094"

  minio:
    image: minio/minio
    command: server /data --console-address ":9001"
    environment:
      MINIO_ROOT_USER: minio
      MINIO_ROOT_PASSWORD: minio123
    ports:
      - "9000:9000"
      - "9001:9001"
    volumes:
      - minio_data:/data

  prometheus:
    image: prom/prometheus:latest
    volumes:
      - ./monitoring/prometheus.yml:/etc/prometheus/prometheus.yml
    ports:
      - "9090:9090"

  grafana:
    image: grafana/grafana:9.0.0
    ports:
      - "3000:3000"
    depends_on:
      - prometheus

  jaeger:
    image: jaegertracing/all-in-one:1.41
    ports:
      - "16686:16686"
      - "6831:6831/udp"

  fraud-analyzer:
    build: ./services/fraud_analyzer
    ports:
      - "8001:8001"
    environment:
      KAFKA_BOOTSTRAP: kafka:9092
      MODEL_PATH: /app/model/model.pkl
      MINIO_URL: http://minio:9000
      MINIO_USER: minio
      MINIO_PASS: minio123
    depends_on:
      - kafka
      - minio

  transaction-ingestor:
    build: ./services/transaction_ingestor
    ports:
      - "8080:8080"
    environment:
      KAFKA_BOOTSTRAP: kafka:9092
    depends_on:
      - kafka

  rule-engine:
    build: ./services/rule_engine
    ports:
      - "7000:7000"

  alert-service:
    build: ./services/alert_service
    ports:
      - "3001:3001"

  ml-pipeline-api:
    image: gcr.io/ml-pipeline/api-server:1.10.0
    ports:
      - "8888:8888"
    environment:
      MINIO_ENDPOINT: minio:9000
      MINIO_ACCESS_KEY: minio
      MINIO_SECRET_KEY: minio123
      MINIO_BUCKET: fraudshield
    depends_on:
      - minio

  ml-pipeline-ui:
    image: gcr.io/ml-pipeline/ui:1.10.0
    ports:
      - "3002:3000"
    environment:
      PIPELINE_API_SERVER: http://ml-pipeline-api:8888
    depends_on:
      - ml-pipeline-api

volumes:
  minio_data:

