global:
  scrape_interval: 5s

scrape_configs:
  - job_name: 'fraud-analyzer'
    static_configs:
      - targets: ['fraud-analyzer:8001']

  - job_name: 'rule-engine'
    static_configs:
      - targets: ['rule-engine:7000']

  - job_name: 'alert-service'
    static_configs:
      - targets: ['alert-service:3001']

  - job_name: "prometheus"
    static_configs:
      - targets: ["localhost:9090"]

