apiVersion: apps/v1
kind: Deployment
metadata:
  name: fraud-analyzer
  namespace: fraudshield
spec:
  replicas: 1
  selector:
    matchLabels:
      app: fraud-analyzer
  template:
    metadata:
      labels:
        app: fraud-analyzer
    spec:
      containers:
      - name: fraud-analyzer
        image: mrunmay1312/dissertation-fraud-analyzer:latest
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 8001
        env:
        - name: MODEL_PATH
          value: /app/model.joblib
