apiVersion: v1
kind: Service
metadata:
  name: fraud-analyzer
  labels:
    app: fraud-analyzer
spec:
  selector:
    app: fraud-analyzer
  ports:
    - port: 8001
      targetPort: 8001
      protocol: TCP

