apiVersion: v1
kind: Service
metadata:
  name: rule-engine
  namespace: fraudshield
  labels:
    app: rule-engine
spec:
  selector:
    app: rule-engine
  ports:
    - port: 8080
      targetPort: 8080
      protocol: TCP
  type: ClusterIP

