apiVersion: v1
kind: Service
metadata:
  name: transaction-ingestor
  labels:
    app: transaction-ingestor
spec:
  selector:
    app: transaction-ingestor
  ports:
    - port: 8080
      targetPort: 8080
      protocol: TCP

